In [1]:
import pandas

In [2]:
import os

In [3]:
from pyiron_atomistics import Project

In [4]:
pr = Project("test")

In [5]:
job = pr.create.job.Lammps("lmp")

In [6]:
job.structure = pr.create.structure.ase.bulk("Al")

In [7]:
murn = job.create_job(pr.job_type.Murnaghan, "murn")

In [8]:
murn.run()

2021-06-11 12:29:21,524 - pyiron_log - WARNING - The job murn is being loaded instead of running. To re-run use the argument 'delete_existing_job=True in create_job'

In [9]:
pr.job_table()

,id,status,chemicalformula,job,subjob,projectpath,project,timestart,timestop,totalcputime,computer,hamilton,hamversion,parentid,masterid
0,1,finished,Al,murn,/murn,None,/home/jovyan/test/,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN
1,2,finished,Al,strain_0_9,/strain_0_9,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
2,3,finished,Al,strain_0_92,/strain_0_92,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
3,4,finished,Al,strain_0_94,/strain_0_94,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
4,5,finished,Al,strain_0_96,/strain_0_96,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
5,6,finished,Al,strain_0_98,/strain_0_98,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
6,7,finished,Al,strain_1_0,/strain_1_0,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
7,8,finished,Al,strain_1_02,/strain_1_02,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
8,9,finished,Al,strain_1_04,/strain_1_04,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
9,10,finished,Al,strain_1_06,/strain_1_06,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
10,11,finished,Al,strain_1_08,/strain_1_08,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
11,12,finished,Al,strain_1_1,/strain_1_1,None,/home/jovyan/test/murn_hdf5/,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,1.0
12,13,finished,Al,murn,/murn,None,/home/jovyan/test/,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN
13,14,finished,Al,strain_0_9,/strain_0_9,None,/home/jovyan/test/,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
14,15,finished,Al,strain_0_92,/strain_0_92,None,/home/jovyan/test/,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
15,16,finished,Al,strain_0_94,/strain_0_94,None,/home/jovyan/test/,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
16,17,finished,Al,strain_0_96,/strain_0_96,None,/home/jovyan/test/,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
17,18,finished,Al,strain_0_98,/strain_0_98,None,/home/jovyan/test/,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
18,19,finished,Al,strain_1_0,/strain_1_0,None,/home/jovyan/test/,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
19,20,finished,Al,strain_1_02,/strain_1_02,None,/home/jovyan/test/,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
20,21,finished,Al,strain_1_04,/strain_1_04,None,/home/jovyan/test/,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
21,22,finished,Al,strain_1_06,/strain_1_06,None,/home/jovyan/test/,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
22,23,finished,Al,strain_1_08,/strain_1_08,None,/home/jovyan/test/,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
23,24,finished,Al,strain_1_1,/strain_1_1,None,/home/jovyan/test/,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN

In [10]:
from pyiron_base import Settings

In [11]:
s = Settings()

In [12]:
s._configuration['sql_connection_string']

'sqlite:////home/jovyan/pyiron.db'

In [13]:
from pyiron_base.archiving.export_archive import export_database

In [14]:
df = export_database(
    project_instance=pr, 
    directory_to_transfer="test",
    archive_directory="."
)
df

,id,status,chemicalformula,job,subjob,project,timestart,timestop,totalcputime,computer,hamilton,hamversion,parentid,masterid
0,0,finished,Al,murn,/murn,./test,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN
1,1,finished,Al,strain_0_9,/strain_0_9,./test/murn_hdf5,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
2,2,finished,Al,strain_0_92,/strain_0_92,./test/murn_hdf5,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
3,3,finished,Al,strain_0_94,/strain_0_94,./test/murn_hdf5,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
4,4,finished,Al,strain_0_96,/strain_0_96,./test/murn_hdf5,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
5,5,finished,Al,strain_0_98,/strain_0_98,./test/murn_hdf5,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
6,6,finished,Al,strain_1_0,/strain_1_0,./test/murn_hdf5,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
7,7,finished,Al,strain_1_02,/strain_1_02,./test/murn_hdf5,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
8,8,finished,Al,strain_1_04,/strain_1_04,./test/murn_hdf5,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
9,9,finished,Al,strain_1_06,/strain_1_06,./test/murn_hdf5,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
10,10,finished,Al,strain_1_08,/strain_1_08,./test/murn_hdf5,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
11,11,finished,Al,strain_1_1,/strain_1_1,./test/murn_hdf5,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0
12,12,finished,Al,murn,/murn,./test,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN
13,13,finished,Al,strain_0_9,/strain_0_9,./test,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
14,14,finished,Al,strain_0_92,/strain_0_92,./test,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
15,15,finished,Al,strain_0_94,/strain_0_94,./test,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
16,16,finished,Al,strain_0_96,/strain_0_96,./test,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
17,17,finished,Al,strain_0_98,/strain_0_98,./test,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
18,18,finished,Al,strain_1_0,/strain_1_0,./test,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
19,19,finished,Al,strain_1_02,/strain_1_02,./test,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
20,20,finished,Al,strain_1_04,/strain_1_04,./test,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
21,21,finished,Al,strain_1_06,/strain_1_06,./test,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
22,22,finished,Al,strain_1_08,/strain_1_08,./test,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN
23,23,finished,Al,strain_1_1,/strain_1_1,./test,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN

In [15]:
s.close_connection()

In [16]:
s._configuration['sql_connection_string'] = 'sqlite:////home/jovyan/pyiron2.db'

In [17]:
s.open_connection()

In [18]:
from pyiron_base.archiving.import_archive import update_id_lst

In [19]:
pr_import = pr.copy()
df["project"] = [os.path.join(
    pr_import.project_path)
    for p in df["project"].values
]
df['projectpath'] = len(df) * [pr_import.root_path]

In [20]:
df

,id,status,chemicalformula,job,subjob,project,timestart,timestop,totalcputime,computer,hamilton,hamversion,parentid,masterid,projectpath
0,0,finished,Al,murn,/murn,/home/jovyan/test/,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN,None
1,1,finished,Al,strain_0_9,/strain_0_9,/home/jovyan/test/,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
2,2,finished,Al,strain_0_92,/strain_0_92,/home/jovyan/test/,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
3,3,finished,Al,strain_0_94,/strain_0_94,/home/jovyan/test/,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
4,4,finished,Al,strain_0_96,/strain_0_96,/home/jovyan/test/,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
5,5,finished,Al,strain_0_98,/strain_0_98,/home/jovyan/test/,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
6,6,finished,Al,strain_1_0,/strain_1_0,/home/jovyan/test/,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
7,7,finished,Al,strain_1_02,/strain_1_02,/home/jovyan/test/,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
8,8,finished,Al,strain_1_04,/strain_1_04,/home/jovyan/test/,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
9,9,finished,Al,strain_1_06,/strain_1_06,/home/jovyan/test/,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
10,10,finished,Al,strain_1_08,/strain_1_08,/home/jovyan/test/,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
11,11,finished,Al,strain_1_1,/strain_1_1,/home/jovyan/test/,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,0.0,None
12,12,finished,Al,murn,/murn,/home/jovyan/test/,2021-06-11 12:15:54.082724,2021-06-11 12:16:19.469274,25.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1#11/11,Murnaghan,0.3.0,None,NaN,None
13,13,finished,Al,strain_0_9,/strain_0_9,/home/jovyan/test/,2021-06-11 12:15:55.410817,2021-06-11 12:15:55.855832,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
14,14,finished,Al,strain_0_92,/strain_0_92,/home/jovyan/test/,2021-06-11 12:15:57.066986,2021-06-11 12:15:57.513902,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
15,15,finished,Al,strain_0_94,/strain_0_94,/home/jovyan/test/,2021-06-11 12:15:58.909651,2021-06-11 12:15:59.320255,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
16,16,finished,Al,strain_0_96,/strain_0_96,/home/jovyan/test/,2021-06-11 12:16:00.910454,2021-06-11 12:16:01.337113,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
17,17,finished,Al,strain_0_98,/strain_0_98,/home/jovyan/test/,2021-06-11 12:16:03.021336,2021-06-11 12:16:03.454184,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
18,18,finished,Al,strain_1_0,/strain_1_0,/home/jovyan/test/,2021-06-11 12:16:05.142801,2021-06-11 12:16:05.597386,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
19,19,finished,Al,strain_1_02,/strain_1_02,/home/jovyan/test/,2021-06-11 12:16:07.514194,2021-06-11 12:16:07.940612,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
20,20,finished,Al,strain_1_04,/strain_1_04,/home/jovyan/test/,2021-06-11 12:16:10.026839,2021-06-11 12:16:10.489974,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
21,21,finished,Al,strain_1_06,/strain_1_06,/home/jovyan/test/,2021-06-11 12:16:12.653450,2021-06-11 12:16:13.090320,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
22,22,finished,Al,strain_1_08,/strain_1_08,/home/jovyan/test/,2021-06-11 12:16:15.509530,2021-06-11 12:16:15.943336,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None
23,23,finished,Al,strain_1_1,/strain_1_1,/home/jovyan/test/,2021-06-11 12:16:18.235777,2021-06-11 12:16:18.720232,0.0,pyiron@jupyter-jan-2djanssen-2dpyiron-2ddb-2dchange-2d5iwggf0s#1,Lammps,0.1,None,NaN,None

In [21]:
# Add jobs to database
job_id_lst = []
for entry in df.dropna(axis=1).to_dict(orient="records"):
    if 'id' in entry:
        del entry['id']
    if 'parentid' in entry:
        del entry['parentid']
    if 'masterid' in entry:
        del entry['masterid']
    if 'timestart' in entry:
        entry["timestart"] = pandas.to_datetime(entry["timestart"])
    if 'timestop' in entry:
        entry["timestop"] = pandas.to_datetime(entry["timestop"])
    if 'username' not in entry: 
        entry["username"] = s.login_user
    job_id = pr_import.db.add_item_dict(par_dict=entry)
    job_id_lst.append(job_id)

In [22]:
# Update parent and master ids
for job_id, masterid, parentid in zip(
    job_id_lst,
    update_id_lst(record_lst=df["masterid"].values, job_id_lst=job_id_lst),
    update_id_lst(record_lst=df["parentid"].values, job_id_lst=job_id_lst),
):
    if not np.isnan(masterid) or not np.isnan(parentid):
        pr_import.db.item_update(
            item_id=job_id,
            par_dict={
                "parentid": parentid, "masterid": masterid
            }
        )

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''